#!/usr/bin/env python3
"""
gpu_kit/probe_decoding_kl.py

PILOT MECHANISM PROBE — Decoding-time instability via first-token logprob KL.

Hypothesis:
    Semantic-preserving rewrites (paraphrase, synonym) cause LARGER divergence
    in the model's first-token next-token distribution than presentation-only
    edits (reorder, format, distractor), at matched edit distance.

Design:
    - Reuse perturbation variants already generated by qwen2.5:3b and validated
      by an independent equivalence judge. We do not re-run perturbation here.
    - For each (orig, variant) pair, query vllm /v1/chat/completions with
        logprobs=True, top_logprobs=20, max_tokens=1, temperature=0.
    - Compute forward KL(orig_dist || variant_dist) over the union of top-20
      tokens, with epsilon smoothing for missing tokens.
    - Per-question paired comparison:
        KL_sem = mean(KL_paraphrase, KL_synonym)
        KL_sur = mean(KL_reorder, KL_format, KL_distractor)
    - Statistical test: paired t-test on KL_sem - KL_sur over n questions.

Pass criteria (pilot):
    p < 0.01 AND mean(KL_sem) / mean(KL_sur) > 1.3

Usage on GPU node (after vllm serve is running on :8000):

    cd agentdiff-emnlp
    source gpu_kit/.venv/bin/activate
    python3 gpu_kit/probe_decoding_kl.py \\
        --variants results/runs_real_qwen25_7b_fix/gsm8k_cot_real_qwen25_7b_fix.jsonl \\
        --model qwen2.5-14b \\
        --base-url http://localhost:8000/v1 \\
        --out results/probe_decoding_kl/qwen25_14b_gsm8k_pilot.json
"""
import argparse
import json
import math
import os
import sys
import time

import requests


def system_prompt():
    """Match the agent prompt style used in agentdiff_v2.py CoT runs.

    We want the first token to be the model's actual reasoning start,
    so we use a minimal CoT instruction without forcing a specific format.
    """
    return ("You are a careful step-by-step problem solver. "
            "Read the question and begin your reasoning.")


def query_logprobs(base_url, model, system, user, top_k=20, timeout=120, max_retries=4):
    """Return dict {token_str: logprob} for the top-k first tokens, or None on error."""
    url = base_url.rstrip("/") + "/chat/completions"
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        "temperature": 0.0,
        "max_tokens": 1,
        "logprobs": True,
        "top_logprobs": top_k,
    }
    for attempt in range(max_retries):
        try:
            r = requests.post(url, json=payload, timeout=timeout,
                              headers={"Content-Type": "application/json"})
            if r.status_code != 200:
                time.sleep(1 + attempt)
                continue
            data = r.json()
            ch = data["choices"][0]
            lp = ch.get("logprobs", {}) or {}
            content = lp.get("content", []) or []
            if not content:
                return None
            tlp = content[0].get("top_logprobs", []) or []
            return {item["token"]: item["logprob"] for item in tlp}
        except Exception:
            time.sleep(1 + attempt)
    return None


def kl_div_top_k(p_logprobs, q_logprobs, eps_logprob=-30.0):
    """Forward KL(P || Q) computed over the union of top-k token sets.

    Tokens missing from either side are assigned eps_logprob (~ exp(-30) prob).
    Both distributions are then renormalized over the union before computing KL.
    Returns float, or None if either dict is empty.
    """
    if not p_logprobs or not q_logprobs:
        return None
    union = set(p_logprobs.keys()) | set(q_logprobs.keys())
    p_ll = [p_logprobs.get(t, eps_logprob) for t in union]
    q_ll = [q_logprobs.get(t, eps_logprob) for t in union]

    # convert log-probs to normalized probabilities (logsumexp -> normalize)
    def lognorm(ll):
        m = max(ll)
        ssum = sum(math.exp(x - m) for x in ll)
        log_z = m + math.log(ssum)
        return [x - log_z for x in ll]

    p_ll = lognorm(p_ll)
    q_ll = lognorm(q_ll)

    kl = 0.0
    for lp, lq in zip(p_ll, q_ll):
        p = math.exp(lp)
        if p > 0:
            kl += p * (lp - lq)
    return kl


def char_edit_distance(s1, s2):
    """Levenshtein at char level, capped for runtime safety."""
    if s1 == s2:
        return 0
    if abs(len(s1) - len(s2)) > 800:
        return max(len(s1), len(s2))
    m, n = len(s1), len(s2)
    if m == 0 or n == 0:
        return max(m, n)
    prev = list(range(n + 1))
    for i in range(1, m + 1):
        cur = [i] + [0] * n
        for j in range(1, n + 1):
            cur[j] = min(cur[j - 1] + 1,
                         prev[j] + 1,
                         prev[j - 1] + (s1[i - 1] != s2[j - 1]))
        prev = cur
    return prev[n]


SEM_TYPES = {"paraphrase", "synonym"}
SUR_TYPES = {"reorder", "format", "distractor"}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--variants", required=True,
                    help="Existing runs_real_*/<bench>_<agent>_real_<slug>.jsonl with perturbation_variants[]")
    ap.add_argument("--model", required=True, help="vllm served-model-name")
    ap.add_argument("--base-url", default="http://localhost:8000/v1")
    ap.add_argument("--out", required=True, help="output json path")
    ap.add_argument("--top-k", type=int, default=20)
    ap.add_argument("--limit", type=int, default=0,
                    help="cap number of questions (0 = all)")
    args = ap.parse_args()

    os.makedirs(os.path.dirname(args.out), exist_ok=True)

    sys_prompt = system_prompt()

    rows = []
    with open(args.variants) as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    if args.limit > 0:
        rows = rows[:args.limit]
    print("[probe] loaded {} questions".format(len(rows)), flush=True)

    # smoke probe
    print("[probe] smoke probe on first question's orig...", flush=True)
    smoke = query_logprobs(args.base_url, args.model, sys_prompt,
                           rows[0]["sample_question"], top_k=args.top_k)
    if smoke is None:
        print("[probe] FATAL: vllm logprobs probe returned None. Server up? top_logprobs supported?",
              file=sys.stderr)
        sys.exit(2)
    print("[probe] smoke ok, top-3 tokens: {}".format(
        sorted(smoke.items(), key=lambda kv: -kv[1])[:3]), flush=True)

    per_question = []
    t0 = time.time()
    for qi, row in enumerate(rows):
        sid = row.get("sample_id", "q{}".format(qi))
        orig_text = row["sample_question"]
        # query orig
        orig_lp = query_logprobs(args.base_url, args.model, sys_prompt, orig_text,
                                 top_k=args.top_k)
        if orig_lp is None:
            print("[probe] skip {}: orig query failed".format(sid))
            continue

        variant_records = []
        for v in row.get("perturbation_variants", []):
            ptype = v.get("perturbation_type")
            vtext = v.get("variant_question") or v.get("question") or ""
            if not vtext:
                continue
            v_lp = query_logprobs(args.base_url, args.model, sys_prompt, vtext,
                                  top_k=args.top_k)
            if v_lp is None:
                continue
            kl = kl_div_top_k(orig_lp, v_lp)
            ed = char_edit_distance(orig_text, vtext)
            ned = ed / max(len(orig_text), 1)
            variant_records.append({
                "perturbation_type": ptype,
                "kl_orig_to_variant": kl,
                "edit_distance": ed,
                "norm_edit_distance": ned,
            })

        per_question.append({
            "sample_id": sid,
            "orig_top_tokens": sorted(orig_lp.items(), key=lambda kv: -kv[1])[:5],
            "variants": variant_records,
        })

        if (qi + 1) % 5 == 0:
            elapsed = time.time() - t0
            rate = (qi + 1) / max(elapsed, 1)
            print("[probe] {}/{}  ({:.1f}s, {:.2f} q/s)".format(
                qi + 1, len(rows), elapsed, rate), flush=True)

    # ---- aggregate & paired test ----
    sem_per_q = []
    sur_per_q = []
    sem_ned_per_q = []
    sur_ned_per_q = []
    for r in per_question:
        sems = [v["kl_orig_to_variant"] for v in r["variants"]
                if v["perturbation_type"] in SEM_TYPES and v["kl_orig_to_variant"] is not None]
        surs = [v["kl_orig_to_variant"] for v in r["variants"]
                if v["perturbation_type"] in SUR_TYPES and v["kl_orig_to_variant"] is not None]
        sem_neds = [v["norm_edit_distance"] for v in r["variants"]
                    if v["perturbation_type"] in SEM_TYPES]
        sur_neds = [v["norm_edit_distance"] for v in r["variants"]
                    if v["perturbation_type"] in SUR_TYPES]
        if sems and surs:
            sem_per_q.append(sum(sems) / len(sems))
            sur_per_q.append(sum(surs) / len(surs))
            sem_ned_per_q.append(sum(sem_neds) / len(sem_neds) if sem_neds else 0)
            sur_ned_per_q.append(sum(sur_neds) / len(sur_neds) if sur_neds else 0)

    n = len(sem_per_q)
    if n < 5:
        verdict = {"status": "insufficient_data", "n_paired": n}
    else:
        diffs = [s - u for s, u in zip(sem_per_q, sur_per_q)]
        mean_diff = sum(diffs) / n
        var = sum((d - mean_diff) ** 2 for d in diffs) / max(n - 1, 1)
        sd = math.sqrt(var)
        se = sd / math.sqrt(n)
        t_stat = mean_diff / se if se > 0 else 0.0
        # cohen's d on paired diffs
        cohens_d = mean_diff / sd if sd > 0 else 0.0

        mean_sem = sum(sem_per_q) / n
        mean_sur = sum(sur_per_q) / n
        ratio = mean_sem / mean_sur if mean_sur > 0 else float("nan")

        # 2-sided p approx via Student-t survival, approximate using Wilson-Hilferty for df=n-1
        # No scipy: approximate p with normal approximation for n>=20, otherwise mark "approx".
        from math import erf, sqrt as msqrt
        if n >= 20:
            p_two = 2 * (1 - 0.5 * (1 + erf(abs(t_stat) / msqrt(2))))
            p_method = "normal_approx (n>=20)"
        else:
            p_two = float("nan")
            p_method = "skipped (n<20, use scipy back home)"

        verdict = {
            "status": "ok",
            "n_paired": n,
            "kl_sem_mean": mean_sem,
            "kl_sur_mean": mean_sur,
            "ratio_sem_over_sur": ratio,
            "kl_sem_minus_sur_mean": mean_diff,
            "paired_t_stat": t_stat,
            "p_two_sided_approx": p_two,
            "p_method": p_method,
            "cohens_d": cohens_d,
            "ned_sem_mean": sum(sem_ned_per_q) / n,
            "ned_sur_mean": sum(sur_ned_per_q) / n,
            "ned_balance_check": ("OK" if abs(sum(sem_ned_per_q) / n - sum(sur_ned_per_q) / n) < 0.15
                                  else "WARN: ned mismatch >0.15, KL gap may be confounded by length"),
        }

    out = {
        "model": args.model,
        "variants_source": args.variants,
        "n_questions_in": len(rows),
        "n_questions_with_orig_lp": len(per_question),
        "verdict": verdict,
        "per_question": per_question,
    }
    with open(args.out, "w") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)

    print("\n[probe] === verdict ===")
    print(json.dumps(verdict, indent=2))
    print("\n[probe] full results -> {}".format(args.out))


if __name__ == "__main__":
    main()
